### ISSUE TITLE
KeyError： ‘interfaceName’

### ISSUE THREAD

**Issue by hdz717** [iromise/fans#5]
sudo sh postprocess.sh 
Traceback (most recent call last):
  File "parse_interface.py", line 138, in <module>
    parse_interfaces()
  File "parse_interface.py", line 117, in parse_interfaces
    parse_one_interface(filename)
  File "parse_interface.py", line 92, in parse_one_interface
    interfaceName =func2svc[funcname]["interfaceName"]
KeyError: 'interfaceName'
ERROR:__main__:readDecryptHandleFromParcelData.xml
ERROR:__main__:Unexpected thing meeted when parsing structure.
cp: cannot stat 'manually/flattenable/reply/*': No such file or directory
cp: cannot stat 'manually/light_flattenable/data/*': No such file or directory
cp: cannot stat 'manually/light_flattenable/reply/*': No such file or directory

**Comment by iromise** [comment]
@HDZ6593515  You can debug according to the log, the log is very clear.
